### ISSUE TITLE
ulimit issue isn't obvious from error message

### ISSUE THREAD

**Issue by mlathara** [GenomicsDB/GenomicsDB#1]
Hit this today and took a while to figure it out. I was using vcf2tiledb to load some vcfs into genomicsdb arrays, and kept running into an error of the sort:

VCF2BinaryException : Could not open file <vcffile> : could not load index (VCF/BCF files must be block compressed and indexed)

And both the vcf and index clearly did exist. Took a while (and some help) to figure out that ulimit wasn't high enough and number of open file descriptors was the problem. Would be very helpful to change the error message somehow to hint at the problem.

**Comment by nalinigans** [comment]
[INFRA-23]

**Comment by nalinigans** [comment]
This has been fixed as per #95
