### ISSUE TITLE
GATK GenomicsDBImport - use list as input

### ISSUE THREAD

**Issue by gabigalata** [GenomicsDB/GenomicsDB#106]
I am using GenomicsDBImport, but since my input file is a file containing a list of file I don't know how to use this as input with GATK along with the -V option. I've been looking for this everywhere, but I can't find this information in the GATK manual.

**Comment by nalinigans** [comment]
Did you take a look at the docs at https://gatk.broadinstitute.org/hc/en-us/articles/360036883491-GenomicsDBImport? You don't use the -V option, instead use --sample-name-map with your input file.
 gatk --java-options "-Xmx4g -Xms4g" \
       GenomicsDBImport \
       --genomicsdb-workspace-path my_database \
      --sample-name-map **<input-file>** 
       -L chr1:1000-10000

The format of your <input-file> should be a tab-delimited text file with each line containing the sample name followed by the path to the vcf file. For example - 
```
sample1      sample1.vcf.gz
sample2      sample2.vcf.gz
sample3      sample3.vcf.gz
```

**Comment by gabigalata** [comment]
Hi @nalinigans, this really helped. I did saw it and thought it was referred to some map format rather than a gvfc list. Thanks!

**Comment by nalinigans** [comment]
Thanks @gabigalata for getting back. Closing this issue for now.
