### ISSUE TITLE
GenomicsDB IO exception has very limited debugging information

### ISSUE THREAD

**Issue by joshwilding4444** [GenomicsDB/GenomicsDB#108]
Originally reported in [#6745](https://github.com/broadinstitute/gatk/issues/6745) in GATK. When running a test, the reporting user got a GenomicsDB JNI error, thrown by jniGenomicsDBInit() in [GenomicsDBQueryStream.java](https://github.com/GenomicsDB/GenomicsDB/blob/master/src/main/java/org/genomicsdb/reader/GenomicsDBQueryStream.java). 

Looking at the C++ code for the native method in [genomicsdb_GenomicsDBQueryStream.cc](https://github.com/GenomicsDB/GenomicsDB/blob/master/src/main/jni/src/genomicsdb_GenomicsDBQueryStream.cc) I find that the method handleJNIException() is called. However, that method takes the generic class std::exception, and the stack trace reports only std::exception, rather than a specific exception. 

Is there a way to determine the specific exception type here?

**Comment by nalinigans** [comment]
Message from std::exception is being gathered at [GenomicsDBQueryStream.cc#L31](https://github.com/GenomicsDB/GenomicsDB/blob/e701905e0bb54765e22119a71038c0e64c85b9c3/src/main/jni/src/genomicsdb_GenomicsDBQueryStream.cc#L31). But for some reason that is not getting propagated properly to the java layer, will look into this, thanks.

**Comment by nalinigans** [comment]
This has been fixed in the 1.3.1 release. Please update your build.gradle/pom.xml genomicsdb dependencies to pick up 1.3.1 - https://mvnrepository.com/artifact/org.genomicsdb/genomicsdb/1.3.1.
