### ISSUE TITLE
[TileDB::FileSystem] Error and FeatureReader to initialize with exception Error

### ISSUE THREAD

**Issue by IBEXCluster** [GenomicsDB/GenomicsDB#122]
Dear team,

The GenomicDB was failed (same command and dataset) with different errors across two file systems.
Summary is as follows: 

**1. BeeGFS file system:** 

$ cat Cq5A.chunk_1.GenomicsDBImport.11705869.err | tail -13
01:08:38.145 INFO  GenomicsDBImport - Starting batch input file preload
01:09:38.916 INFO  GenomicsDBImport - Finished batch preload
01:09:38.916 INFO  GenomicsDBImport - Importing batch 1 with 564 samples
[TileDB::FileSystem] Error: (write_to_file) Cannot write to file; File writing error; path=/ibex/scratch/projects/c2071/1000quinoa/naga/1128_Phase2/RESULTS/gVCF/Cq5A.1/Cq5A$1$8993623/__06ef12cd-3e3e-445b-8a17-78d392d6e35347261215135488_1600294179899/ExcessHet.tdb; errno=121(Remote I/O error)
[TileDB::WriteState] Error: Cannot write segment to file.
02:44:19.847 erro  NativeGenomicsDB - pid=208539 tid=208928 VariantStorageManagerException exception : Error while writing to TileDB array
TileDB error message : [TileDB::WriteState] Error: Cannot write segment to file
[TileDB::FileSystem] Error: (write_to_file) Cannot write to file; File writing error; path=/ibex/scratch/projects/c2071/1000quinoa/naga/1128_Phase2/RESULTS/gVCF/Cq5A.1/Cq5A$1$8993623/__06ef12cd-3e3e-445b-8a17-78d392d6e35347261215135488_1600294179899/ExcessHet.tdb; errno=121(Remote I/O error)
terminate called after throwing an instance of 'std::exception'
  what():  std::exception

**2. NFS file system**

$ cat Cq5A.chunk_1.GenomicsDBImport.11739158.err | tail -13
11:49:12.994 INFO  GenomicsDBImport - Starting batch input file preload
11:52:16.216 INFO  GenomicsDBImport - Shutting down engine
[September 21, 2020 11:52:16 AM AST] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 8.28 minutes.
Runtime.totalMemory()=19555942400

A USER ERROR has occurred: Couldn't read file. Error was: Failure while waiting for FeatureReader to initialize  with exception: org.broadinstitute.hellbender.exceptions.UserException: Failed to create reader from file:///ibex/scratch/projects/c2071/1000quinoa/OUT/Sept2020/VCF/S7E1_batch2.snps.indels.g.vcf.gz
 

Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.
 

**Note:**  

1.  export TILEDB_DISABLE_FILE_LOCKING=1 environment variable was set before running GenomicDB
2. The same NFS file system error was observed in BeeGFS file system during the execution of GenomicDB with different chromosome name/chunks. I used to overcome this issues 

**Background:**

GATK version: 4.1.8
GenomicDB native library version: 1.3.0-e701905
**Command used:**
gatk GenomicsDBImport --variant $INPUT --genomicsdb-workspace-path $gVCF/$ChrName.$size --intervals $ChrName:$Start-$End --reader-threads $CORES"

Where, 

$INPUT is list of Haplotypecaller gVCF files from 1128 samples. 

$ChrName is Cq5A 

$size is 1,2,3 ..8 (8 chunks)

$ChrName:$Start-$End is based on this below summary:

**Cq5A split into 8 parts and here is the summary.**

$ cat Chromosome_distribution.txt | grep Cq5A
Cq5A split into 8 parts
Chromosome name:Cq5A, Chunk number: 1, and Interval(Start:1-End:8993623)
Chromosome name:Cq5A, Chunk number: 2, and Interval(Start:8993624-End:17987246)
Chromosome name:Cq5A, Chunk number: 3, and Interval(Start:17987247-End:26980869)
Chromosome name:Cq5A, Chunk number: 4, and Interval(Start:26980870-End:35974492)
Chromosome name:Cq5A, Chunk number: 5, and Interval(Start:35974493-End:44968115)
Chromosome name:Cq5A, Chunk number: 6, and Interval(Start:44968116-End:53961738)
Chromosome name:Cq5A, Chunk number: 7, and Interval(Start:53961739-End:62955361)
Chromosome name:Cq5A, Chunk number: 8, and Interval(Start:62955362-End:64666259)

**Observations:** 

1. Chunks 1,2,3,7 and 8 are failed (Chunks 4,5 and 6 are successful) in BeeGFS
2. Chunks 1,2,3,4 and 7 are failed (chunks 5,6 and 8 are successful) in NFS. 
3. For example:

At BeeGFS:
$ cat Cq5A.chunk_5.GenomicsDBImport.11705873.out 
Tool returned:
true

At NFS
$ cat Cq5A.chunk_5.GenomicsDBImport.11739162.out 
Tool returned:
true

**System environment:** 

OS: CentOS Linux release 7.7.1908 (Core)
Java version: 1.8.0_242
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

Thanks and Regards,
Naga

**Comment by nalinigans** [comment]
@IBEXCluster, can you try this additional argument `--genomicsdb-shared-posixfs-optimizations` with the gatk command? This option disables file locking without environment variables and has optimizations to improve the usability for shared posix filesystems such as `NFS`, `BeeGFS`, `Lustre`.  If this argument does not help, please let us know if you are open to try a debug version of the native GenomicsDB library, we can post instructions on how to build/use them.

**Comment by IBEXCluster** [comment]
Dear @nalinigans 
Thanks for your suggestion. 

> additional argument --genomicsdb-shared-posixfs-optimizations with the gatk command? 

The file system related errors are disappear after adding the above arguments.

However, I'm getting the IO Exception runtime error. Please see this below error log: 

01:44:08.744 INFO  GenomicsDBImport - Finished batch preload
01:44:08.744 INFO  GenomicsDBImport - Importing batch 1 with 1128 samples
02:20:20.871 INFO  GenomicsDBImport - Shutting down engine
[September 22, 2020 2:20:20 AM AST] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 44.69 minutes.
Runtime.totalMemory()=24256184320
htsjdk.samtools.util.RuntimeIOException: java.io.IOException: Remote I/O error
	at htsjdk.tribble.readers.TabixIteratorLineReader.readLine(TabixIteratorLineReader.java:48)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.readNextRecord(TabixFeatureReader.java:170)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:205)
	at htsjdk.tribble.TabixFeatureReader$FeatureIterator.next(TabixFeatureReader.java:149)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport$1$NoMnpIterator.next(GenomicsDBImport.java:851)
	at org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport$1$NoMnpIterator.next(GenomicsDBImport.java:842)
	at org.genomicsdb.importer.GenomicsDBImporterStreamWrapper.next(GenomicsDBImporterStreamWrapper.java:110)
	at org.genomicsdb.importer.GenomicsDBImporter.doSingleImport(GenomicsDBImporter.java:580)
	at org.genomicsdb.importer.GenomicsDBImporter.lambda$null$2(GenomicsDBImporter.java:703)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: Remote I/O error
	at java.io.RandomAccessFile.readBytes(Native Method)
	at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
	at htsjdk.samtools.seekablestream.SeekableFileStream.read(SeekableFileStream.java:85)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at htsjdk.samtools.seekablestream.SeekableBufferedStream.read(SeekableBufferedStream.java:133)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:571)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBytes(BlockCompressedInputStream.java:560)
	at htsjdk.samtools.util.BlockCompressedInputStream.processNextBlock(BlockCompressedInputStream.java:525)
	at htsjdk.samtools.util.BlockCompressedInputStream.nextBlock(BlockCompressedInputStream.java:468)
	at htsjdk.samtools.util.BlockCompressedInputStream.readBlock(BlockCompressedInputStream.java:458)
	at htsjdk.samtools.util.BlockCompressedInputStream.available(BlockCompressedInputStream.java:196)
	at htsjdk.samtools.util.BlockCompressedInputStream.read(BlockCompressedInputStream.java:241)
	at htsjdk.tribble.readers.TabixReader.readLine(TabixReader.java:215)
	at htsjdk.tribble.readers.TabixReader.access$300(TabixReader.java:48)
	at htsjdk.tribble.readers.TabixReader$IteratorImpl.next(TabixReader.java:434)
	at htsjdk.tribble.readers.TabixIteratorLineReader.readLine(TabixIteratorLineReader.java:46)
	... 12 more

Note:
GenomicsDBImport using HTSJDK Version: 2.22.0 and Picard Version: 2.22.8

**Comment by nalinigans** [comment]
Can you post your gatk command in its entirety? I am almost inclined to say that it could be a Java heap issue? What are your Java heap options(-Xmx, -Xms) if you have used them?

@mlathara, @kgururaj, any ideas on what could be happening?

**Comment by IBEXCluster** [comment]
@nalinigans 

> Can you post your gatk command in its entirety?

gatk GenomicsDBImport --variant $INPUT --genomicsdb-workspace-path $gVCF/$ChrName.$size --intervals $ChrName:$Start-$End --reader-threads $CORES --genomicsdb-shared-posixfs-optimizations true

I'm not using Java heap/stack options.

Further, I observed the same error appeared again for different chromosome chunk.

01:38:08.221 INFO  GenomicsDBImport - Initializing engine
01:44:52.385 INFO  IntervalArgumentCollection - Processing 152079 bp from intervals
01:44:52.386 INFO  GenomicsDBImport - Done initializing engine
01:44:52.634 INFO  GenomicsDBLibLoader - GenomicsDB native library version : 1.3.0-e701905
01:44:52.871 INFO  GenomicsDBImport - Vid Map JSON file will be written to /ibex/projects/c2071/results_posix/gVCF/MK159176.1.1/vidmap.json
01:44:52.871 INFO  GenomicsDBImport - Callset Map JSON file will be written to /ibex/projects/c2071/results_posix/gVCF/MK159176.1.1/callset.json
01:44:52.871 INFO  GenomicsDBImport - Complete VCF Header will be written to /ibex/projects/c2071/results_posix/gVCF/MK159176.1.1/vcfheader.vcf
01:44:52.871 INFO  GenomicsDBImport - Importing to workspace - /ibex/projects/c2071/results_posix/gVCF/MK159176.1.1
01:44:52.873 INFO  ProgressMeter - Starting traversal
01:44:52.874 INFO  ProgressMeter -        Current Locus  Elapsed Minutes     Batches Processed   Batches/Minute
01:44:53.110 INFO  GenomicsDBImport - Starting batch input file preload
01:45:43.835 INFO  GenomicsDBImport - Shutting down engine
[September 22, 2020 1:45:43 AM AST] org.broadinstitute.hellbender.tools.genomicsdb.GenomicsDBImport done. Elapsed time: 7.60 minutes.
Runtime.totalMemory()=11526471680

A USER ERROR has occurred: Couldn't read file. Error was: Failure while waiting for FeatureReader to initialize  with exception: org.broadinstitute.hellbender.exceptions.UserException: Failed to create reader from file:///ibex/scratch/projects/c2071/1000quinoa/OUT/Sept2020/VCF/S3A8_batch1.snps.indels.g.vcf.gz

Set the system property GATK_STACKTRACE_ON_USER_EXCEPTION (--java-options '-DGATK_STACKTRACE_ON_USER_EXCEPTION=true') to print the stack trace.

**Comment by nalinigans** [comment]
```
Caused by: java.io.IOException: Remote I/O error
at java.io.RandomAccessFile.readBytes(Native Method)
at java.io.RandomAccessFile.read(RandomAccessFile.java:377)
at htsjdk.samtools.seekablestream.SeekableFileStream.read(SeekableFileStream.java:85)
at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
```
This makes me believe that this is an issue on your `beegfs` filesystem configuration. Are you able to look through the logs on the `beegfs` server for any clues? I have no experience with the `beegfs` system. Also, what is the output of running `ulimit -a` on your client?

**Comment by mlathara** [comment]
Another knob that may be worth trying...you could try a `--batch-size 50`. By default, the import process imports all the samples in one shot -- but this requires more available file handles and memory. Since you have >1000 samples, that _might_ be causing some of the issues. Specifying batch size lowers the requirements on file handles and memory, and so may help.

Also, just to confirm, you tried `--genomicsdb-shared-posixfs-optimizations true` on both beegfs and nfs?

**Comment by IBEXCluster** [comment]
@nalinigans Thanks!
>This makes me believe that this is an issue with your beegfs filesystem configuration

I will request the system admin for the system logs and getback to you!

>ulimit -a on your client?

```
core file size          (blocks, -c) unlimited
data seg size           (kbytes, -d) unlimited
scheduling priority             (-e) 0
file size               (blocks, -f) unlimited
pending signals                 (-i) 1542395
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) 2097152
open files                      (-n) 131072
pipe size            (512 bytes, -p) 8
POSIX message queues     (bytes, -q) 819200
real-time priority              (-r) 0
stack size              (kbytes, -s) unlimited
cpu time               (seconds, -t) unlimited
max user processes              (-u) 1542395
virtual memory          (kbytes, -v) unlimited
file locks                      (-x) unlimited
```

Do we need to increase the number of pipe size and open files? 
Also, Numbers of `file-max` are set to 39 millions. Is this sufficient?  
Please suggest!

**Comment by IBEXCluster** [comment]
@mlathara 

Many thanks! 

On NFS file system, I used  `--genomicsdb-shared-posixfs-optimizations true` option and it's failed with `java.io.IOException: Remote I/O error`. 

Indeed, it's a great idea to try with `--batch-size 50`. 

On BeeGFS, the GenomicDB jobs are submitted with `--genomicsdb-shared-posixfs-optimizations true` and `--batch-size 50`. I will update you my progress.

**Comment by kgururaj** [comment]
How much memory do you allocate for each job? I suspect we're running into some weird memory issue

For a problematic partition, I would allocate 50 GB of memory for the job with 40 GB for Java (rest for the C++ modules):

    ./gatk --java-options '-Xmx35g -Xms5g' <other_args>

If that succeeds, then you can try reducing the memory allocated.

**Comment by IBEXCluster** [comment]
@mlathara 

My submitted jobs are successfully completed using `--genomicsdb-shared-posixfs-optimizations true` and `--batch-size 50`. Many thanks for this suggestions. 🏆

@kgururaj 

Thanks for suggesting me to use Java heap memory. I was using this below Java options (e.g.: 50GB, 100GB, ... for heap memory and  500GB, 1TB, ... main memory) for other project (Wheat genome, which is 5x times bigger than human genome).   

```
JAVAOPT="--java-options \"-XX:-UseGCOverheadLimit -Xmx$JMEM -Xms$JMEM -XX:+PrintGCDetails -DGATK_STACKTRACE_ON_USER_EXCEPTION=true\""
gatk $JAVAOPT GenomicsDBImport --variant $INPUT --genomicsdb-workspace-path $gVCF/$ChrName.$size --intervals $ChrName:$Start-$End --reader-threads $CORES"
```

This works very well for smaller number of samples (example 20-80 samples)! ⭐

However, my jobs are failed when the number of samples increases!  

`A USER ERROR has occurred: Couldn't read file. Error was: Failure while waiting for FeatureReader to initialize  with exception: java.lang.OutOfMemoryError: GC overhead limit exceeded`


To overcome this issues, I was using `“--genomicsdb-update-workspace-path”` for next batch of additional 100+ upcoming samples. I may give it a try with `--genomicsdb-shared-posixfs-optimizations true` and `--batch-size 50` options for larger number of samples once it's ready (mostly next month). 

Overall, I'm good to import all the samples to the GenomicDB (e.g. 50 samples at a time with multiple batches).
Many thanks for all your suggestions and time.

**Comment by mlathara** [comment]
Great. Closing this as resolved.
