### ISSUE TITLE
Maven wget url invalid

### ISSUE THREAD

**Issue by boyangzhao** [GenomicsDB/GenomicsDB#169]
It seems when running the `install_prereqs.sh`, during the maven installation step, it is trying to wget from the following url, 
`https://www-us.apache.org/dist/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz`. However, this led to the error `wget: unable to resolve host address 'www-us.apache.org'`.  The host www-us.apache.org is no longer valid. Should this url be updated?

**Comment by nalinigans** [comment]
Thanks @boyangzhao for the heads up on this issue. Changed the maven download url to `https://downloads.apache.org/maven/maven-3/$MAVEN_VERSION/binaries/apache-maven-$MAVEN_VERSION-bin.tar.gz` and the fix is currently merged into the `develop` branch.  Let us know if this helps.

**Comment by nalinigans** [comment]
The maven url for wget has been pulled into master now. Thanks.

Also, note that the R bindings have been moved to https://github.com/GenomicsDB/GenomicsDB-R and the Python bindings can be installed via PyPi using `pip install genomicsdb`.
