### ISSUE TITLE
Add incremental support to GenomicsDBImport

### ISSUE THREAD

**Issue by nalinigans** [GenomicsDB/GenomicsDB#18]
See https://github.com/broadinstitute/gatk/issues/4773.

Will have to persist the callset.json files at the workspace/array/fragment level in GenomicsDB as opposed to the workspace level as it is currently done.

**Comment by mlathara** [comment]
We tackled this here: https://github.com/GenomicsDB/GenomicsDB/pull/28

Closing the issue.
