### ISSUE TITLE
Import should automatically increase buffer size as needed

### ISSUE THREAD

**Issue by mlathara** [GenomicsDB/GenomicsDB#226]
Currently the import tools expect to have a buffer size set that allows reading an entire VCF line (size_per_column_partition: see [here](https://github.com/GenomicsDB/GenomicsDB/wiki/Importing-VCF-data-into-GenomicsDB#execution-parameters-for-the-import-program)). 

It would be much more user friendly to have the import process automatically increase the buffer size as needed if the initial buffer size does not fit the input VCF line.

**Comment by nalinigans** [comment]
@mlathara, are there any error messages from GenomicsDS when the `size_per_column_partition` is not sufficient? Can easily write a unit test to figure it out if you are not sure.

**Comment by nalinigans** [comment]
Currently, we see this when the buffer size to hold a VCF line is not sufficient -
```
~/GenomicsDB/install/bin: ./vcf2genomicsdb -r 2 ws/loader.json 
[TileDB::StorageManager] Error: Cannot load array schema; Array '/Users/nalini/GenomicsDB/install/bin/ws/3$1$198022430' does not exist.
libc++abi: terminating with uncaught exception of type File2TileDBBinaryException: File2TileDBBinaryException : read_one_line_fully && "Buffer did not have space to hold a line fully - increase buffer size"
Abort trap: 6
```

**Comment by nalinigans** [comment]
I think this is fixed by https://github.com/GenomicsDB/GenomicsDB/pull/270.
