### ISSUE TITLE
Compilation on Ubuntu jammy fails in aws-cpp-sdk

### ISSUE THREAD

**Issue by lima1** [GenomicsDB/GenomicsDB#287]
I tried installing GenomicsDB following the Wiki using an Ubuntu jammy Docker image. Looks like the compilation fails here:
```

/root/awssdk-install/1.8.x/src/awssdk-build/aws-cpp-sdk-core/source/utils/crypto/openssl/CryptoImpl.cpp:373:31: error: ‘int HMAC_CTX_reset(HMAC_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
  373 |                 HMAC_CTX_reset(m_ctx);
```

A workaround (also used in aws-cpp-sdk: https://github.com/aws/aws-sdk-cpp/issues/1582) is setting -Wno-error=deprecated-declarations, but I'm not sure where I have to provide this; my amateurish attempts failed.

**Comment by mlathara** [comment]
You have a few options here:
- the latest `develop` branch should have the changes you need, which you can try
- you could use the image we publish at [ghcr.io](https://github.com/GenomicsDB/GenomicsDB/pkgs/container/genomicsdb/91379502?tag=develop). Currently, the `develop` tagged image is based off Lunar and includes the executables but not the jar
- you can build your own version of the published image based on jammy using a command like `docker build --build-arg os=ubuntu:jammy .` from the repository root

**Comment by lima1** [comment]
Thanks @mlathara . Compiling and installing worked with develop.

When installing the GenomicsDB-R bindings, I however now get following error complaining about a missing genomicsdb_status.h.  

```
ls /opt/GenomicsDB/include/
genomicsdb_exception.h  genomicsdb.h  genomicsdb_utils.h
```

`config.log:/opt/GenomicsDB/include/genomicsdb_utils.h:43:10: fatal error: genomicsdb_status.h: No such file or directory`

Installed using:
```
cmake -DCMAKE_INSTALL_PREFIX=$GENOMICSDB_PATH -DCMAKE_BUILD_TYPE=Release ./GenomicsDB
make
make install
```

**Comment by nalinigans** [comment]
@lima1, the GenomicsDB-R bindings are out-of-date w.r.t the GenomicsDB api. We can work on getting it working by next week. Would that be OK?
