### ISSUE TITLE
ERROR: failed to solve: failed to compute cache key

### ISSUE THREAD

**Issue by youngbee12** [GenomicsDB/GenomicsDB#306]
Building 0.1s (12/13)                                                                                                                                                             docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                            0.0s
 => => transferring dockerfile: 2.32kB                                                                                                                                                          0.0s
 => [internal] load .dockerignore                                                                                                                                                               0.0s
 => => transferring context: 34B                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/library/ubuntu:latest                                                                                                                                0.0s
 => [internal] load build context                                                                                                                                                               0.0s
 => => transferring context: 40.18kB                                                                                                                                                            0.0s
 => [release 1/6] FROM docker.io/library/ubuntu                                                                                                                                                 0.0s
 => CACHED [full 2/4] COPY . /build/GenomicsDB/                                                                                                                                                 0.0s
 => CACHED [full 3/4] WORKDIR /build/GenomicsDB                                                                                                                                                 0.0s
 => CACHED [full 4/4] RUN ./scripts/prereqs/install_prereqs.sh full &&    useradd -r -U -m genomicsdb &&    ./scripts/install_genomicsdb.sh genomicsdb /tmp/genomicsdb/install true             0.0s
 => CACHED [release 2/6] COPY ./scripts/prereqs /build                                                                                                                                          0.0s
 => CACHED [release 3/6] WORKDIR /build                                                                                                                                                         0.0s
 => CACHED [release 4/6] RUN ./install_prereqs.sh release &&    useradd -r -U -m genomicsdb                                                                                                     0.0s
 => ERROR [release 5/6] COPY --from=full /usr/local/bin/*genomicsdb* /usr/local/bin/gt_mpi_gather /usr/local/bin/vcf* /tmp/genomicsdb/install/bin/                                              0.0s
------
 > [release 5/6] COPY --from=full /usr/local/bin/*genomicsdb* /usr/local/bin/gt_mpi_gather /usr/local/bin/vcf* /tmp/genomicsdb/install/bin/:
------
Dockerfile:57
--------------------
  55 |         useradd -r -U -m ${user}
  56 |     
  57 | >>> COPY --from=full /usr/local/bin/*genomicsdb* /usr/local/bin/gt_mpi_gather /usr/local/bin/vcf* ${install_dir}/bin/
  58 |     
  59 |     USER ${user}
--------------------
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 667d83a6-2fb1-41e6-a5d0-fe43821cfc6b::2e3shtccixb8ww9htyrm6vzh8: "/usr/local/bin/gt_mpi_gather": not found

**Comment by mlathara** [comment]
Can you share how you invoked the Dockerfile? Looks like you may have overriden the `install_dir` ARG and the current Dockerfile seems to have a bug which assumes that the intermediate stage installs to `/usr/local`. 

You can either choose to not override the `install_dir` ARG (to be clear, it is only choosing where to install inside the docker image in this case, not your local filesystem) or just try to use our pre-built image
```
docker pull ghcr.io/genomicsdb/genomicsdb:develop
```

**Comment by nalinigans** [comment]
Closing as the fix has been released - https://github.com/GenomicsDB/GenomicsDB/releases/tag/v1.5.1
