### ISSUE TITLE
Python library?

### ISSUE THREAD

**Issue by Hoeze** [GenomicsDB/GenomicsDB#38]
Hi, is there some Python interface for GenomicsDB?

**Comment by nalinigans** [comment]
Not yet. We are currently working on an external `query` api to the native GenomicsDB library and R bindings. For importing VCFs into GenomicsDB, you will still have to build [tools](https://github.com/GenomicsDB/GenomicsDB/tree/master/tools) and use as outlined in the [wiki](https://github.com/GenomicsDB/GenomicsDB/wiki/Importing-VCF-data-into-GenomicsDB)

We are starting work on a query Python library very soon. Please let us know of your specific requirements.

**Comment by Hoeze** [comment]
Thanks for the quick answer @nalinigans!
I'd like to use GenomicsDB for storing massive amounts of variant data and executing the following query types:
1) fetch all variants a certain individual has
2) fetch all individuals with a certain variant

I'd need especially (1) for efficiently fetching reference + alternative sequence of individuals in a certain genomic region.

**Comment by nalinigans** [comment]
See https://github.com/GenomicsDB/GenomicsDB-Python
