### ISSUE TITLE
ubuntu install help

### ISSUE THREAD

**Issue by anthonypalacios** [GenomicsDB/GenomicsDB#53]
I'd like some help troubleshooting the install process on ubuntu 16.04

attached is the output for cmake & make

[genomecmake.txt](https://github.com/GenomicsDB/GenomicsDB/files/3433019/genomecmake.txt)
[genomemake.txt](https://github.com/GenomicsDB/GenomicsDB/files/3433020/genomemake.txt)

**Comment by nalinigans** [comment]
Did you follow the instructions outlined in https://github.com/GenomicsDB/GenomicsDB/wiki/Building-GenomicsDB-Version-0.4.0?
What versions of cmake, gcc and protobuf are you using?
Can you attach your exact cmake command?
The Travis build for GenomicsDB is using ubuntu/trusty and a good place to look for ubuntu options is https://github.com/GenomicsDB/GenomicsDB/blob/master/.travis.yml.

FWIW: I just tested on docker image with ubuntu 16.04 and could build successfully.
```
**genomicsdb@4f0934e87018**:~$ uname -a
Linux 4f0934e87018 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
**genomicsdb@4f0934e87018:**~$ gcc --version
gcc (Ubuntu 4.9.4-2ubuntu1~16.04) 4.9.4
**genomicsdb@4f0934e87018:**~$ cmake --version
cmake version 3.5.1
**genomicsdb@4f0934e87018:**~$ protoc --version
libprotoc 3.0.2
```

**Comment by kgururaj** [comment]
Can you run the make command with VERBOSE=1

    make VERBOSE=1

**Comment by anthonypalacios** [comment]
Thank you for the help…

cmake --version
cmake version 3.5.1

gcc --version
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609

protoc --version
libprotoc 3.0.2

cmake /software/GenomicsDB -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/software -DSAFESTRINGLIB_DIR=/software/safestringlib -DSAFESTRINGLIB_INCLUDE_DIR=/software/safestringlib/include >  genomedb_make.txt

make BUILD=release OPENMP=1 -j 8 -> genomemake.txt

Anthony Palacios
Programmer Analyst
DGIT | Digital Technology
UCLA Health Information Technology
Office: 310-267-0573
apalacios@mednet.ucla.edu<mailto:apalacios@mednet.ucla.edu>

**Comment by anthonypalacios** [comment]
[genomemake.txt](https://github.com/GenomicsDB/GenomicsDB/files/3437355/genomemake.txt)

**Comment by nalinigans** [comment]
@anthonypalacios, I still can't make out what is going wrong from the logs. I did try a docker image with ubuntu:16.04 this time with all your versions of cmake/gcc/etc. and could build/install GenomicsDB. Only difference - I did not use safestring. Can you try in a new, empty build directory?
```
cd <path_to_build_directory>
cmake /software/GenomicsDB -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/software <path_to_genomicsdb_repository>
make VERBOSE=1
```

**Comment by nalinigans** [comment]
@anthonypalacios, were you successful in building?

**Comment by anthonypalacios** [comment]
yes...thank you for trying to help.

i was missing some packages/dependencies
