### ISSUE TITLE
protobuf version

### ISSUE THREAD

**Issue by shubhamchandak94** [GenomicsDB/GenomicsDB#62]
Hi,
I tried to follow the instructions by first building protobuf 3.0.2, but got an error "google/protobuf/port_def.inc: No such file or directory". Then I did git checkout 3.7.x inside protobuf followed by the installation and that succeeded. 
Regards,
Shubham

**Comment by nalinigans** [comment]
@shubhamchandak94, thanks. Will update the wiki appropriately as some of the Protobuf versions mentioned have been archived.

**Comment by nalinigans** [comment]
No longer an issue as protobuf is built as part of GenomicsDB build itself.
