### ISSUE TITLE
REF, ALT, QUAL, FILTER, INFO fields stored multiple times for each sample?

### ISSUE THREAD

**Issue by shubhamchandak94** [GenomicsDB/GenomicsDB#63]
Hi,
If I import a VCF file into genomicsDB containing many samples, say something from the 1000 genome project, are the fields that are common to all samples (the ones mentioned in the subject line) stored in each TileDB cell? Or are they stored just once per variant?
Regards,
Shubham

**Comment by kgururaj** [comment]
Hello Shubham,
  Yes, all the common fields are stored in every TileDB cell for each sample.

GenomicsDB was developed primarily for storing variant data from many individual samples (many VCFs, each VCF with 1 sample) and then jointly querying/processing the data. It doesn't work well when the variant data from multiple samples is already combined into a single VCF.

We have seen this issue before and gave some thought to it. In the end, I gave up trying to make multi-sample VCF import into GenomicsDB efficient.

**Comment by shubhamchandak94** [comment]
Thanks for the clarification!
