### ISSUE TITLE
Couldn't create GenomicsDBFeatureReader

### ISSUE THREAD

**Issue by xinkaitong** [GenomicsDB/GenomicsDB#81]
when i excuted comand 
"gatk --java-options "-Xmx4g" GenotypeGVCFs \
-R ${ref} \
-V gendb://chr1_database \
--tmp-dir=${temp_dir} \
-O DB76.chr1.vcf.gz".
problem always occured with message "[TileDB::StorageManager] Error: Cannot lock consolidation filelock; Cannot lock ....... A USER ERROR has occurred: Couldn't create GenomicsDBFeatureReader".
i was very confused with that problem for a month. who can help me? thanks so much!

**Comment by nalinigans** [comment]
What version of gatk are you using?
Is `chr1_database` on a shared filesystem like NFS or Lustre?
Can you try setting environment variable TILEDB_DISABLE_FILE_LOCKING=true and then try again?

**Comment by xinkaitong** [comment]
> What version of gatk are you using?
> Is `chr1_database` on a shared filesystem like NFS or Lustre?
> Can you try setting environment variable TILEDB_DISABLE_FILE_LOCKING=true and then try again?

i use GATK v4.1.4.1 to conduct this. the chr1_database is a directory on a lustre system. 
i have never try setting environment variable TILEDB_DISABLE_FILE_LOCKING=true, but then i will try it.

**Comment by nalinigans** [comment]
What is the output of `find chr1_database -name .__consolidation_lock`? Are any files found?

**Comment by xinkaitong** [comment]
> What is the output of `find chr1_database -name .__consolidation_lock`? Are any files found?

yes, it will find "chr1_database/1$1$16613/.__consolidation_lock".

**Comment by nalinigans** [comment]
> yes, it will find "chr1_database/1$1$16613/.__consolidation_lock".

Thanks. Can you please paste the entire error message if possible?

**Comment by jayceejiao** [comment]
Hi,
I also encounter the same problem. my .__consolidation_lock file is empty and I have uploaded the error file. I also find that for a chromosome with a length of less than 130 MB, it works. But for the large chromosome, it won't work.

[err.txt](https://github.com/GenomicsDB/GenomicsDB/files/4252022/err.txt)

**Comment by jayceejiao** [comment]
I am also using gatk-4.1.4.1. I also called the SNP data from RNA-Seq reads (smaller data set) for this species, using the same genome, GenotypeGVCFs works for all chromosomes.

**Comment by nalinigans** [comment]
@xinkaitong, Did you workaround file locking issue? If the `TILEDB_DISABLE_FILE_LOCKING=1`, did not work, can you please see if you are able to invoke `flock chr1_database/1$1$16613/.__consolidation_lock` from the command line? If you are not able to do that, then you might be having issues with permissions on acquiring the lock. One workaround for now would be from the command line or shell script
```
% rm -f chr1_database/1$1$16613/.__consolidation_lock
% TILEDB_DISABLE_FILE_LOCKING=1 gatk --java-options "-Xmx4g" GenotypeGVCFs -R ${ref} -V gendb://chr1_database --tmp-dir=${temp_dir} -O DB76.chr1.vcf.gz".
```

**Comment by nalinigans** [comment]
@jayceejiao, your problem seems to be unrelated to file locking. You might be having a memory issue - please search the [GATK forum](https://gatkforums.broadinstitute.org/gatk/search?adv=&author=&cat=100&comment_answer=1&comment_c=1&date=&discussion_d=1&discussion_question=1&group_group=1&search=GenomicsDB) for possible solutions.

**Comment by xinkaitong** [comment]
@nalinigans when i excuted code `TILEDB_DISABLE_FILE_LOCKING=1`` gatk --java-options "-Xmx4g" GenotypeGVCFs -R ${ref} -V gendb://chr1_database --tmp-dir=${temp_dir} -O DB76.chr1.vcf.gz"`, the problem was solved. really grateful to you! _^ v ^_
